---
- name: IOS network facts
  hosts: ios_devices
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Gathering IOS facts
      cisco.ios.ios_facts:

    - name: Show hostname and version
      ansible.builtin.debug:
        msg: "The hostname is {{ ansible_facts['net_hostname'] }} and the version is {{ ansible_facts['net_version'] }}"

    - name: Display all facts for hosts
      ansible.builtin.debug:
        var: ansible_facts
